/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author alejandrofranco
 */
public class inicio extends javax.swing.JFrame {

    String textoUnSoloParqueadero = "\n Esta simulación analiza individualmente un parqueadero estándar \n mediante el modelo de colas M/M/S para distintos tamaños de \n parqueadero."
                                    +" Pequeños (15 cupos), medianos (42 cupos) y grandes \n (90 cupos). En ella puede ajustar los parámetros Lambda (λ) \n (Número de vehículos por hora),"
                                    + " Miu (μ) (Número de minutos promedio \n que un espacio de parqueo permanece ocupado) y n (Número de \n vehículos en el sistema) con el fin de poder determinar:\n\n" +
                                     " - L: Valor esperado de número de vehículos en el sistema.\n" +
                                     " - Lq: Valor esperado de vehículos en la cola.\n" +
                                     " - W: Tiempo medio de espera en el sistema.\n" +
                                     " - Wq: Tiempo medio de espera en la cola.\n" +
                                     " - Ro: Factor de utilización del sistema (intensidad de tráfico).\n" +
                                     " - Pn: Probabilidad que n vehículos estén en el sistema.\n" +
                                     " - Pw: Probabilidad de que un nuevo vehículo tenga que esperar. ";
    
    String textoMultiplesSoloParqueaderos = "\n A partir de los parqueaderos caracterizados con ayuda de una serie de \n"
                                            + " encuestas, se ubican en un mapa de la ciudad de Bogotá con el fin de\n"
                                            + " poder introducir en el sistema distintas cantidades de vehículos, se\n"
                                            + " busca observar el desempeño total del sistema vehículos-parqueaderos\n"
                                            + " entorno a la dinámica de atención y operación teniendo en cuenta cada\n"
                                            + " valor parametrizado por parqueadero.\n" +"\n" 
                                            +" El sistema permite introducir el tiempo en segundos (que simularán\n"
                                            +" horas de operación), también permite introducir el número de vehículos\n"
                                            +" que se desea observar para que sean analizados en conjunto con la\n"
                                            +" dinámica de funcionamiento de los parqueaderos.";
    
    public inicio() {
        initComponents();
        // Ubica en el centro la ventana por defecto
        this.setLocationRelativeTo(null);
        // Texto por defecto para un solo parqueadero
        jTextAreaMsjSimulacion.setText(textoUnSoloParqueadero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoSimulacion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonUnParqueadero = new javax.swing.JRadioButton();
        jRadioButtonMultiplesParqueaderos = new javax.swing.JRadioButton();
        jRadioButtonAlgoritmosDeBusqueda = new javax.swing.JRadioButton();
        jButtonSimular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMsjSimulacion = new javax.swing.JTextArea();
        Labelimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulación de Parqueaderos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Simulación /Análisis", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        buttonGroupTipoSimulacion.add(jRadioButtonUnParqueadero);
        jRadioButtonUnParqueadero.setSelected(true);
        jRadioButtonUnParqueadero.setText("Un solo parqueadero");
        jRadioButtonUnParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUnParqueaderoActionPerformed(evt);
            }
        });

        buttonGroupTipoSimulacion.add(jRadioButtonMultiplesParqueaderos);
        jRadioButtonMultiplesParqueaderos.setText("Múltiples parqueaderos");
        jRadioButtonMultiplesParqueaderos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMultiplesParqueaderosActionPerformed(evt);
            }
        });

        buttonGroupTipoSimulacion.add(jRadioButtonAlgoritmosDeBusqueda);
        jRadioButtonAlgoritmosDeBusqueda.setText("Alg. de búsqueda tradicional");
        jRadioButtonAlgoritmosDeBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlgoritmosDeBusquedaActionPerformed(evt);
            }
        });

        jButtonSimular.setText("Ingresar");
        jButtonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMultiplesParqueaderos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSimular))
                    .addComponent(jRadioButtonAlgoritmosDeBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jRadioButtonUnParqueadero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonUnParqueadero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMultiplesParqueaderos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAlgoritmosDeBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSimular)
                .addContainerGap())
        );

        jTextAreaMsjSimulacion.setEditable(false);
        jTextAreaMsjSimulacion.setColumns(20);
        jTextAreaMsjSimulacion.setLineWrap(true);
        jTextAreaMsjSimulacion.setRows(5);
        jTextAreaMsjSimulacion.setText("Un solo parqueadero");
        jScrollPane1.setViewportView(jTextAreaMsjSimulacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        Labelimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/parqueadero 14 cupos.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Labelimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Labelimagen)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimularActionPerformed
        
        if(jRadioButtonUnParqueadero.isSelected()) {
            SimUnSoloParqueadero s_uno = new SimUnSoloParqueadero(this, true);
            s_uno.setVisible(true);
        } else if(jRadioButtonMultiplesParqueaderos.isSelected()) {
            SimMultiplesParqueaderos s_mul = new SimMultiplesParqueaderos(this, true);
            s_mul.setVisible(true);
        } else if(jRadioButtonAlgoritmosDeBusqueda.isSelected()) {
            AlgoritmosBusqueda a_busqueda = new AlgoritmosBusqueda(this, true);
            a_busqueda.setVisible(true);
        }
    }//GEN-LAST:event_jButtonSimularActionPerformed

    private void jRadioButtonUnParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUnParqueaderoActionPerformed
        // TODO add your handling code here:
        jTextAreaMsjSimulacion.setText(textoUnSoloParqueadero);
        ImageIcon icon = new ImageIcon("./src/app/imagenes/parqueadero 14 cupos.png");
        Labelimagen.setIcon(icon);
        Labelimagen.setText("");
        
    }//GEN-LAST:event_jRadioButtonUnParqueaderoActionPerformed

    private void jRadioButtonMultiplesParqueaderosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMultiplesParqueaderosActionPerformed
        // TODO add your handling code here:
        jTextAreaMsjSimulacion.setText(textoMultiplesSoloParqueaderos);
        ImageIcon icon = new ImageIcon("./src/app/imagenes/bogota_map_vertical.jpg");
        Labelimagen.setIcon(icon);
        Labelimagen.setText("");
    }//GEN-LAST:event_jRadioButtonMultiplesParqueaderosActionPerformed

    private void jRadioButtonAlgoritmosDeBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlgoritmosDeBusquedaActionPerformed
        jTextAreaMsjSimulacion.setText("En construcción ...");
        ImageIcon icon = new ImageIcon("./src/app/imagenes/algoritmos_busqueda.png");
        Labelimagen.setIcon(icon);
        Labelimagen.setText("");
    }//GEN-LAST:event_jRadioButtonAlgoritmosDeBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS x".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelimagen;
    private javax.swing.ButtonGroup buttonGroupTipoSimulacion;
    private javax.swing.JButton jButtonSimular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAlgoritmosDeBusqueda;
    private javax.swing.JRadioButton jRadioButtonMultiplesParqueaderos;
    private javax.swing.JRadioButton jRadioButtonUnParqueadero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMsjSimulacion;
    // End of variables declaration//GEN-END:variables
}
